### your site title here

title: Michal Ferber
description: love Jesus, love each other, work hard and play hard

baseurl: /michalferber.com #name of GitHub repository
url: "" #custom url to be used instead of GitHub repository
email: michalaferber@pm.me


highlighter: rouge
markdown: kramdown

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
facebook: "michalaferber"
gab: "michalaferber"
getter: "michalaferber"
github: "michalaferber"
instagram: "michalaferber"
locals: "michalaferber"
linkedin: "michalaferber"
signal: "michalaferber"
telegram: "michalaferber"
tiktok: "michalaferber"
truth: "michalaferber"
twitter: "michalaferber"
whatsapp: "michalaferber"

highlighter: rouge
markdown: kramdown

# Tracker
analytics:

#optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:path/

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
